language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key"
    token:
      secure: 9ecffa1f44a5274dd1e189ffabf57b9f34c34223

script:
  - mvn clean cobertura:cobertura package

after_success:
  - mvn coveralls:report
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
