language: java

jdk:
  - openjdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11

branches:
  only:
    - master

notifications:
  email: false

script: "mvn cobertura:cobertura"

after_success:
  - mvn coveralls:report
  - bash <(curl -s https://codecov.io/bash)
