language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email: false

script: "mvn clean cobertura:cobertura"

after_success:
  - mvn coveralls:report
  - bash <(curl -s https://codecov.io/bash)
