language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "han-feng-github"
    token:
      secure: "9ecffa1f44a5274dd1e189ffabf57b9f34c34223"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean cobertura:cobertura package

after_success:
  - mvn coveralls:report
  - mvn sonar:sonar
  - bash <(curl -s https://codecov.io/bash)
